# Generated by Django 3.2.2 on 2021-05-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default='Smallville', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(default='CA', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Name of the company in 200 characters or less.', max_length=200, unique=True),
        ),
    ]
