# Generated by Django 3.2.2 on 2021-05-11 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0005_auto_20210511_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
