# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build status

on:
  push:
    branches: [ master, dev ]

env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CANVAS_TOKEN: ${{ secrets.CANVAS_TOKEN }}
  CANVAS_URL: ${{ secrets.CANVAS_URL }}
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
  CSCI_SALT: ${{ secrets.CSCI_SALT }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt install graphviz
        python -m pip install --upgrade pipenv
        pipenv install --dev --ignore-pipfile --deploy
    - name: Install and setup code coverage tool
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
    - name: Run tests
      run: |
        pipenv run pytest --cov-report xml --cov-report term
    - name: Report coverage to codeclimate
      run: |
        ./cc-test-reporter after-build --exit-code 0
    - name: Submit to Canvas
      if: false # Set this to true to submit
      run: |
        pipenv run python submit.py        

